version: '3.7'


services:
  db:
    image: mysql
    command: --max-allowed-packet=64MB --local-infile=ON
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo          
      - MYSQL_PASSWORD=password123

  matomo:
    build: 
      context: .     
      dockerfile: Dockerfile 
    restart: always    
    volumes:
      - ./config.ini.tmpl.php:/var/www/html/config/config.ini.tmpl.php
    env_file:
      - .env.dev          
    ports:
      - 8080:80

  cron:
    build: 
      context: .
      dockerfile: Dockerfile.cron     
    restart: always    
    volumes:
      - ./config.ini.tmpl.php:/var/www/html/config/config.ini.tmpl.php
    env_file:
      - .env.dev

volumes:
  db:  
